export const ProductActionsType = {
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PRODUCT: 'GET_PRODUCT',
    Add_PRODUCT: 'Add_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    PRODUCTS_LOADING: 'PRODUCTS_LOADING'
}
